### PR TITLE
MiltyDraftModifications

### PR DESCRIPTION
**Pull request by DangerousGoods**
rebased from main to include changes made post fork, have left customized hand label instead of using the helper function.

-- # Added alternate tiers
-- # Tiers based on a bag draft system I was working on, Basic premise is the first tier is systems with 2
-- # or more planets and no tech skips. Second tier are the systems with 2 or more planets with tech skips
-- # and the legendaries, and Atlas / Lodor. Third tier is the single planet systems + Quann
-- # These tiers are more likely to cause slices that don't meet minimum requirements
-- # (Original idea took the remaing unchosen tier 2 systems and randomized them with tier 3 - would help with min req issues)
-- # Added option button to split wormholes better (and prevent Cormund/Everra being together)
-- # Changed forced wormhole options to track between blue and red tile selections
-- # Changed blue tile hand builder to prevent relocating reserved tileSet
-- # Started adding in a hand weight calculator, with the idea that if Cormund or Everra are to be in a
-- # slice that they go into the worst ones. -- would like some feedback on this as opinion on a slice
-- # can vary along which what races are available, also not taking into consideration planet traits.. as
-- # a 4 of a kind slice could get a higher rating.
-- # Cormund / Everra - these skew the slices, and idea would be to put a placeholder system image in place for
-- # both nebula / gravity rifts i.e. use the non planet system image with a ?? and make it lucky dip for selection.

### CODE REVIEW

**Comment by darrellanderson** [comment]
Skimming though this look reasonable to me, I asked Milty (who wrote the tier / selection code) to take a peek.  I feel like it might make sense to just make this the standard when enabling more wormholes.  (Conceivably could remove all options and just make this **the** tile selection logic; I wonder how many MiltyDraft games are using the base selection vs extra wormholes anyhow.)

**Comment by darrellanderson** [comment]
(Also I'm not a git wizard but it looks like only MiltyDraft.ttslua actually needs to be merged; not sure why it wants to fold in other things that are already committed.)

**Comment by darrellanderson** [comment]
It looks like this change replaces the tier lists, is that just to be able to make 9 slices or are those necessary for the other logic?  If it's just for 9 maybe it should use the old tiers unless making 9 slices (with the caveat that slices may be weaker / higher variance)?

**Comment by markmiltenburg** [comment]
Looks fine. I think Tile 72 in tier 1 doesn't fit the criteria you laid out for tiers.

The new tiers look like they'll potentially present some more unbalanced slices compared to the current tiers, but I think we can test that out and see player feedback.

**Comment by DangerousGoods** [comment]
yeah not quite sure what happened with the pull request, probably something to do with merge up into the fork and back down again :| should just be the one file to merge as mentioned.

Tile 72 in tier 1 should be Tile 75 - typo :/

Tier list change was primarily to mix up the original bag draft system and was more curious to see how it would go in the slice system. Slices do appear weaker with the tier changes, potentially not a terrible thing though if players need to compete more for resources...

**Comment by darrellanderson** [comment]
As I see it there are two independent changes here:

1. New tier list (following the above rules) with enough tiles to permit 9 slices.
2. Optional wormhole restriction to prevent more than one wormhole per slice.

(2) seems generally good, so rather than adding another option I think it makes sense to make that the default.  I see you print a warning if "extra wormholes/legendaries" isn't enabled, it seems it should be safe to use the restricted wormhole count even if not adding more, no?

I am curious how the expanded tier list affects variance; I'll build a giant set and look at it.

**Comment by DangerousGoods** [comment]
Correct for two independent changes. 

do you want me to do anything more from this point or will you just incorporate the WH restrictions as you see fit?

**Comment by darrellanderson** [comment]
I think I've got it from here, will reach out if I hit any snags.  Thanks!

**Comment by darrellanderson** [comment]
I've folded in just the MiltyDraft.ttslua changes, and made this the default behavior (I didn't want to add another setting, this seemed fine to have always on).  I'm going to close this without merging in the pull request because of the other files tagging along, but the meat of this is now in the repo.  Thanks for the contribution!

**Comment by darrellanderson** [comment]
(This isn't live in the public mod yet, should be in the next update.)

**Comment by DangerousGoods** [comment]
cheers! glad I could an help in some way.

**Pull request closed without merging**
